services:
  redis:
    image: redis
    container_name: redis
    volumes:
      - redis_data:/root/redis
    env_file:
      - .env
    ports:
      - "6379:6379"
    restart: unless-stopped

  app:
    build: .
    container_name: youtube-tumbnails
    volumes:
      - "./logs:/logs"
      - "./secrets:/secrets"
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - redis
    env_file:
      - .env
    restart: unless-stopped
      

volumes:
  redis_data: