services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped

  app:
    build: .
    container_name: youtube-tumbnails
    volumes:
      - "./logs:/logs"
      - "./secrets:/secrets"
    env_file:
      - .env
      

volumes:
  pg_data: